name: CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: React Build
        uses: 
          - actions/checkout@v3
          - actions/setup-node@v3
        run: |
          npm i
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true

  smoke_test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Runs a smoke test
        run: curl --fail https://bejewelled-mermaid-54e346.netlify.app

    